"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FileHandler = exports.getValueAtPath = exports.checkPath = exports.getAttributeByPath = void 0;
const attributesHandler_1 = require("./attributesHandler");
Object.defineProperty(exports, "getAttributeByPath", { enumerable: true, get: function () { return attributesHandler_1.getAttributeByPath; } });
const checkObj_1 = require("./checkObj");
Object.defineProperty(exports, "getValueAtPath", { enumerable: true, get: function () { return checkObj_1.getValueAtPath; } });
Object.defineProperty(exports, "checkPath", { enumerable: true, get: function () { return checkObj_1.checkPath; } });
const filehandler_1 = require("./filehandler");
exports.FileHandler = filehandler_1.default;
